# Generated by Django 2.2.1 on 2019-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_type', models.CharField(max_length=20)),
                ('boat_image', models.ImageField(upload_to='../static/images/boats')),
                ('line_1', models.CharField(max_length=200)),
                ('line_2', models.CharField(max_length=200)),
                ('line_3', models.CharField(max_length=200)),
                ('line_4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='../static/images/slider')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('photo', models.ImageField(upload_to='../static/images/testimonial')),
            ],
        ),
    ]
